import type {
    StatCardData,
    RevenueCategoryBreakdown,
    TopProduct,
    RecentOrder,
    InventoryAlert,
} from '../../types/dashboardTypes';
import { formatVND } from '../../utils/formatters';

export const mockStatCards: StatCardData[] = [
    {
        id: '1',
        title: 'Doanh Thu Hôm Nay',
        value: 48520000,
        formattedValue: formatVND(48520000),
        change: 14.8,
        isPositive: true,
        timeframe: 'so với hôm qua',
        iconName: 'revenue',
    },
    {
        id: '2',
        title: 'Tổng Số Đơn Hàng',
        value: 342,
        formattedValue: '342 đơn',
        change: 8.4,
        isPositive: true,
        timeframe: 'so với hôm qua',
        iconName: 'orders',
    },
    {
        id: '3',
        title: 'Giá Trị TB / Đơn Hàng',
        value: 141870,
        formattedValue: formatVND(141870),
        change: 5.9,
        isPositive: true,
        timeframe: 'so với hôm qua',
        iconName: 'avgOrder',
    },
    {
        id: '4',
        title: 'Cảnh Báo Tồn Kho',
        value: 14,
        formattedValue: '14 sản phẩm',
        change: -2.1,
        isPositive: false,
        timeframe: 'cần nhập thêm hàng',
        iconName: 'lowStock',
    },
];

export const mockCategories: RevenueCategoryBreakdown[] = [
    {
        category: 'Đồ Ăn Nhanh & Thức Uống Nóng/Lạnh',
        percentage: 42,
        amount: 20378400,
        color: '#E31837', // Circle K Red
    },
    {
        category: 'Hàng Tiêu Dùng & Đóng Gói',
        percentage: 28,
        amount: 13585600,
        color: '#FFC72C', // Circle K Yellow
    },
    {
        category: 'Bánh Kẹo & Snack Thức Uống',
        percentage: 18,
        amount: 8733600,
        color: '#10B981',
    },
    {
        category: 'Mỹ Phẩm & Tiện Ích Cá Nhân',
        percentage: 12,
        amount: 5822400,
        color: '#6366F1',
    },
];

export const mockTopProducts: TopProduct[] = [
    {
        key: '1',
        sku: 'CK-FROSTER-01',
        name: 'Nước Tuyết Froster Slushie (Ly Lớn 22oz)',
        category: 'Thức Uống Lạnh',
        price: 25000,
        quantitySold: 184,
        totalRevenue: 4600000,
        stockLevel: 450,
        image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=100&q=80',
        status: 'Best Seller',
    },
    {
        key: '2',
        sku: 'CK-NOODLE-02',
        name: 'Mì Trộn Circle K Trứng Chả Lụa Special',
        category: 'Đồ Ăn Nhanh',
        price: 32000,
        quantitySold: 142,
        totalRevenue: 4544000,
        stockLevel: 85,
        image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=100&q=80',
        status: 'Best Seller',
    },
    {
        key: '3',
        sku: 'CK-COFFEE-03',
        name: 'Cà Phê Sữa Đá Sài Gòn 100% Arabica',
        category: 'Thức Uống',
        price: 20000,
        quantitySold: 135,
        totalRevenue: 2700000,
        stockLevel: 210,
        image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=100&q=80',
        status: 'In Stock',
    },
    {
        key: '4',
        sku: 'CK-HOTDOG-04',
        name: 'Bánh Mì Hot Dog Xốt Phô Mai Cay',
        category: 'Đồ Ăn Nhanh',
        price: 28000,
        quantitySold: 98,
        totalRevenue: 2744000,
        stockLevel: 14,
        image: 'https://images.unsplash.com/photo-1619740455993-9e612b1af08a?w=100&q=80',
        status: 'Low Stock',
    },
    {
        key: '5',
        sku: 'CK-SNACK-05',
        name: 'Bánh Lay\'s Vị Táo Đỏ Cay Nóng 95g',
        category: 'Snack',
        price: 22000,
        quantitySold: 86,
        totalRevenue: 1892000,
        stockLevel: 120,
        image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=100&q=80',
        status: 'In Stock',
    },
];

export const mockRecentOrders: RecentOrder[] = [
    {
        key: '1',
        orderId: 'ORD-20260825-089',
        time: '08:28 AM',
        cashier: 'Nguyễn Văn Minh (NV04)',
        itemsCount: 4,
        totalAmount: 112000,
        paymentMethod: 'MoMo',
        status: 'Completed',
    },
    {
        key: '2',
        orderId: 'ORD-20260825-088',
        time: '08:24 AM',
        cashier: 'Trần Thị Thu (NV02)',
        itemsCount: 2,
        totalAmount: 45000,
        paymentMethod: 'ZaloPay',
        status: 'Completed',
    },
    {
        key: '3',
        orderId: 'ORD-20260825-087',
        time: '08:19 AM',
        cashier: 'Nguyễn Văn Minh (NV04)',
        itemsCount: 7,
        totalAmount: 238000,
        paymentMethod: 'Cash',
        status: 'Completed',
    },
    {
        key: '4',
        orderId: 'ORD-20260825-086',
        time: '08:12 AM',
        cashier: 'Lê Hoàng Nam (NV01)',
        itemsCount: 1,
        totalAmount: 25000,
        paymentMethod: 'Card',
        status: 'Completed',
    },
    {
        key: '5',
        orderId: 'ORD-20260825-085',
        time: '08:05 AM',
        cashier: 'Trần Thị Thu (NV02)',
        itemsCount: 3,
        totalAmount: 89000,
        paymentMethod: 'MoMo',
        status: 'Processing',
    },
];

export const mockInventoryAlerts: InventoryAlert[] = [
    {
        id: '1',
        productName: 'Bánh Mì Hot Dog Xốt Phô Mai Cay',
        sku: 'CK-HOTDOG-04',
        category: 'Đồ Ăn Nhanh',
        currentStock: 14,
        minStock: 30,
        suggestedReorder: 50,
        urgency: 'high',
    },
    {
        id: '2',
        productName: 'Sữa Tươi Tiệt Trùng Vinamilk 180ml',
        sku: 'CK-MILK-12',
        category: 'Hàng Tiêu Dùng',
        currentStock: 8,
        minStock: 40,
        suggestedReorder: 100,
        urgency: 'high',
    },
    {
        id: '3',
        productName: 'Bánh Bao Nhân Thịt Trứng Cút Circle K',
        sku: 'CK-BAO-01',
        category: 'Đồ Ăn Nhanh',
        currentStock: 12,
        minStock: 25,
        suggestedReorder: 40,
        urgency: 'medium',
    },
    {
        id: '4',
        productName: 'Khăn Gấy Ướt Tiện Lợi Circle K 20 tờ',
        sku: 'CK-TISSUE-09',
        category: 'Tiện Ích',
        currentStock: 19,
        minStock: 30,
        suggestedReorder: 60,
        urgency: 'low',
    },
];
