import {
  BRANCH_KIND,
  RECORD_STATUS,
  REGION,
  type Branch,
} from '@/types';

/**
 * Module 3 – Dữ liệu chi nhánh mẫu.
 *
 * Gồm 1 kho tổng (DC) + 7 cửa hàng trải trên 3 miền. Kho tổng `CK-DC01`
 * là nguồn xuất hàng cho các phiếu luân chuyển nội bộ ở module 9.
 */
export const mockBranches: Branch[] = [
  {
    id: 'br-dc01',
    code: 'CK-DC01',
    name: 'Kho Tổng Circle K Miền Nam',
    kind: BRANCH_KIND.DistributionCenter,
    region: REGION.South,
    province: 'TP. Hồ Chí Minh',
    district: 'Huyện Bình Chánh',
    addressLine: 'Lô C2-1, KCN Vĩnh Lộc, Đường Nguyễn Thị Tú',
    phone: '028 3765 1100',
    openingHours: '06:00 - 22:00',
    managerName: 'Phạm Quốc Hưng',
    managerId: 'emp-001',
    employeeCount: 24,
    areaSqm: 4200,
    monthlyRevenue: 0,
    openedAt: '2019-03-15',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0101',
    code: 'CK-0101',
    name: 'Circle K Bùi Viện',
    kind: BRANCH_KIND.Store,
    region: REGION.South,
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 1',
    addressLine: '185 Bùi Viện, Phường Phạm Ngũ Lão',
    phone: '028 3920 4411',
    openingHours: '24/7',
    managerName: 'Trần Văn Anh',
    managerId: 'emp-002',
    employeeCount: 12,
    areaSqm: 132,
    monthlyRevenue: 1_482_600_000,
    openedAt: '2020-06-01',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0102',
    code: 'CK-0102',
    name: 'Circle K Trần Quốc Thảo',
    kind: BRANCH_KIND.Store,
    region: REGION.South,
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 3',
    addressLine: '78 Trần Quốc Thảo, Phường Võ Thị Sáu',
    phone: '028 3932 7788',
    openingHours: '24/7',
    managerName: 'Nguyễn Thị Kim Ngân',
    managerId: 'emp-003',
    employeeCount: 10,
    areaSqm: 118,
    monthlyRevenue: 1_146_200_000,
    openedAt: '2020-11-20',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0103',
    code: 'CK-0103',
    name: 'Circle K Thảo Điền',
    kind: BRANCH_KIND.Store,
    region: REGION.South,
    province: 'TP. Hồ Chí Minh',
    district: 'TP. Thủ Đức',
    addressLine: '25 Nguyễn Văn Hưởng, Phường Thảo Điền',
    phone: '028 3744 2299',
    openingHours: '24/7',
    managerName: 'Lê Hoàng Nam',
    managerId: 'emp-004',
    employeeCount: 11,
    areaSqm: 145,
    monthlyRevenue: 1_318_900_000,
    openedAt: '2021-04-08',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0104',
    code: 'CK-0104',
    name: 'Circle K Phan Xích Long',
    kind: BRANCH_KIND.Store,
    region: REGION.South,
    province: 'TP. Hồ Chí Minh',
    district: 'Quận Phú Nhuận',
    addressLine: '112 Phan Xích Long, Phường 2',
    phone: '028 3517 6633',
    openingHours: '24/7',
    managerName: 'Đỗ Thanh Tuyền',
    managerId: 'emp-005',
    employeeCount: 9,
    areaSqm: 108,
    monthlyRevenue: 962_400_000,
    openedAt: '2022-02-14',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0201',
    code: 'CK-0201',
    name: 'Circle K Hoàn Kiếm',
    kind: BRANCH_KIND.Store,
    region: REGION.North,
    province: 'Hà Nội',
    district: 'Quận Hoàn Kiếm',
    addressLine: '42 Hàng Bài, Phường Hàng Bài',
    phone: '024 3936 5511',
    openingHours: '24/7',
    managerName: 'Vũ Đình Trọng',
    managerId: 'emp-006',
    employeeCount: 11,
    areaSqm: 126,
    monthlyRevenue: 1_205_700_000,
    openedAt: '2021-09-30',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0202',
    code: 'CK-0202',
    name: 'Circle K Cầu Giấy',
    kind: BRANCH_KIND.Store,
    region: REGION.North,
    province: 'Hà Nội',
    district: 'Quận Cầu Giấy',
    addressLine: '215 Xuân Thủy, Phường Dịch Vọng Hậu',
    phone: '024 3767 8822',
    openingHours: '24/7',
    managerName: 'Hoàng Minh Châu',
    managerId: 'emp-007',
    employeeCount: 10,
    areaSqm: 134,
    monthlyRevenue: 1_089_300_000,
    openedAt: '2022-07-11',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0301',
    code: 'CK-0301',
    name: 'Circle K Trần Phú Đà Nẵng',
    kind: BRANCH_KIND.Store,
    region: REGION.Central,
    province: 'Đà Nẵng',
    district: 'Quận Hải Châu',
    addressLine: '88 Trần Phú, Phường Hải Châu 1',
    phone: '0236 3821 4477',
    openingHours: '06:00 - 24:00',
    managerName: 'Ngô Bảo Khang',
    managerId: 'emp-008',
    employeeCount: 8,
    areaSqm: 96,
    monthlyRevenue: 684_500_000,
    openedAt: '2023-05-19',
    status: RECORD_STATUS.Active,
  },
  {
    id: 'br-0105',
    code: 'CK-0105',
    name: 'Circle K Nguyễn Trãi (Tạm đóng)',
    kind: BRANCH_KIND.Store,
    region: REGION.South,
    province: 'TP. Hồ Chí Minh',
    district: 'Quận 5',
    addressLine: '456 Nguyễn Trãi, Phường 8',
    phone: '028 3923 1100',
    openingHours: '24/7',
    managerName: 'Bùi Thị Mai Lan',
    managerId: 'emp-009',
    employeeCount: 0,
    areaSqm: 102,
    monthlyRevenue: 0,
    openedAt: '2021-01-25',
    status: RECORD_STATUS.Inactive,
  },
];

/** Kho tổng – nguồn xuất hàng nội bộ. */
export const DISTRIBUTION_CENTER_ID = 'br-dc01';

/** Chỉ các cửa hàng đang hoạt động (có quầy POS). */
export const activeStores = mockBranches.filter(
  (branch) =>
    branch.kind === BRANCH_KIND.Store && branch.status === RECORD_STATUS.Active,
);

/** Tra cứu nhanh chi nhánh theo id. */
export const branchById = (id: string): Branch | undefined =>
  mockBranches.find((branch) => branch.id === id);

/** Tên chi nhánh theo id, trả về "Toàn chuỗi" nếu id là null. */
export const branchNameById = (id: string | null): string => {
  if (id === null) return 'Toàn chuỗi';
  return branchById(id)?.name ?? 'Không xác định';
};