import {
  PRODUCT_UNIT,
  RECORD_STATUS,
  type Product,
  type ProductUnit,
} from '@/types';
import { categoryNameById } from './categories';
import { supplierNameById } from './suppliers';

/**
 * Module 5 – Sản phẩm.
 *
 * `imageUrl` để trống có chủ ý: MVP không host asset sản phẩm, các component
 * (`ProductThumb`) sẽ tự fallback sang emoji của danh mục. Nhờ vậy lưới POS
 * không phải chờ tải ảnh từ mạng ngoài.
 */

/** Dữ liệu thô, `categoryName`/`supplierName` được suy ra bên dưới. */
interface RawProduct {
  id: string;
  sku: string;
  barcode: string;
  name: string;
  categoryId: string;
  unit: ProductUnit;
  costPrice: number;
  salePrice: number;
  vatPercent: number;
  supplierId: string;
  minStock: number;
  maxStock: number;
  isPerishable: boolean;
  shelfLifeDays: number;
  status?: Product['status'];
}

const rawProducts: RawProduct[] = [
  // ── Đồ ăn nóng (cat-01) ─────────────────────────────────────────────────────────────
  {
    id: 'prd-001',
    sku: 'CK-HOTFOOD-01',
    barcode: '8934567000011',
    name: 'Bánh Bao Nhân Thịt Trứng Cút',
    categoryId: 'cat-01',
    unit: PRODUCT_UNIT.Piece,
    costPrice: 11_000,
    salePrice: 18_000,
    vatPercent: 8,
    supplierId: 'sup-4',
    minStock: 25,
    maxStock: 80,
    isPerishable: true,
    shelfLifeDays: 2,
  },
  {
    id: 'prd-002',
    sku: 'CK-HOTFOOD-02',
    barcode: '8934567000028',
    name: 'Bánh Mì Hot Dog Xốt Phô Mai Cay',
    categoryId: 'cat-01',
    unit: PRODUCT_UNIT.Piece,
    costPrice: 17_500,
    salePrice: 28_000,
    vatPercent: 8,
    supplierId: 'sup-4',
    minStock: 30,
    maxStock: 90,
    isPerishable: true,
    shelfLifeDays: 1,
  },
  {
    id: 'prd-003',
    sku: 'CK-HOTFOOD-03',
    barcode: '8934567000035',
    name: 'Xúc Xích Đức Nướng C.P Size L',
    categoryId: 'cat-01',
    unit: PRODUCT_UNIT.Piece,
    costPrice: 13_000,
    salePrice: 22_000,
    vatPercent: 8,
    supplierId: 'sup-4',
    minStock: 40,
    maxStock: 120,
    isPerishable: true,
    shelfLifeDays: 2,
  },
  {
    id: 'prd-004',
    sku: 'CK-HOTFOOD-04',
    barcode: '8934567000042',
    name: 'Mì Trộn Circle K Trứng Chả Lụa',
    categoryId: 'cat-01',
    unit: PRODUCT_UNIT.Cup,
    costPrice: 19_000,
    salePrice: 32_000,
    vatPercent: 8,
    supplierId: 'sup-3',
    minStock: 20,
    maxStock: 70,
    isPerishable: true,
    shelfLifeDays: 1,
  },
  {
    id: 'prd-005',
    sku: 'CK-HOTFOOD-05',
    barcode: '8934567000059',
    name: 'Cơm Chiên Dương Châu Hộp',
    categoryId: 'cat-01',
    unit: PRODUCT_UNIT.Piece,
    costPrice: 24_000,
    salePrice: 39_000,
    vatPercent: 8,
    supplierId: 'sup-4',
    minStock: 15,
    maxStock: 50,
    isPerishable: true,
    shelfLifeDays: 1,
  },
  {
    id: 'prd-006',
    sku: 'CK-HOTFOOD-06',
    barcode: '8934567000066',
    name: 'Khoai Tây Chiên Lắc Phô Mai',
    categoryId: 'cat-01',
    unit: PRODUCT_UNIT.Cup,
    costPrice: 12_000,
    salePrice: 25_000,
    vatPercent: 8,
    supplierId: 'sup-4',
    minStock: 20,
    maxStock: 60,
    isPerishable: true,
    shelfLifeDays: 1,
  },

  // ── Nước giải khát (cat-02) ──────────────────────────────────────────────────────
  {
    id: 'prd-007',
    sku: 'CK-DRINK-01',
    barcode: '8934588000015',
    name: 'Pepsi Cola Lon 330ml',
    categoryId: 'cat-02',
    unit: PRODUCT_UNIT.Can,
    costPrice: 7_200,
    salePrice: 12_000,
    vatPercent: 10,
    supplierId: 'sup-1',
    minStock: 96,
    maxStock: 480,
    isPerishable: false,
    shelfLifeDays: 270,
  },
  {
    id: 'prd-008',
    sku: 'CK-DRINK-02',
    barcode: '8934588000022',
    name: '7Up Chanh Lon 330ml',
    categoryId: 'cat-02',
    unit: PRODUCT_UNIT.Can,
    costPrice: 7_200,
    salePrice: 12_000,
    vatPercent: 10,
    supplierId: 'sup-1',
    minStock: 96,
    maxStock: 480,
    isPerishable: false,
    shelfLifeDays: 270,
  },
  {
    id: 'prd-009',
    sku: 'CK-DRINK-03',
    barcode: '8934588000039',
    name: 'Trà Ô Long Tea+ Chai 455ml',
    categoryId: 'cat-02',
    unit: PRODUCT_UNIT.Bottle,
    costPrice: 8_500,
    salePrice: 14_000,
    vatPercent: 10,
    supplierId: 'sup-7',
    minStock: 72,
    maxStock: 360,
    isPerishable: false,
    shelfLifeDays: 300,
  },
  {
    id: 'prd-010',
    sku: 'CK-DRINK-04',
    barcode: '8934588000046',
    name: 'Nước Suối Aquafina 500ml',
    categoryId: 'cat-02',
    unit: PRODUCT_UNIT.Bottle,
    costPrice: 4_200,
    salePrice: 8_000,
    vatPercent: 10,
    supplierId: 'sup-7',
    minStock: 120,
    maxStock: 600,
    isPerishable: false,
    shelfLifeDays: 365,
  },
  {
    id: 'prd-011',
    sku: 'CK-DRINK-05',
    barcode: '8934588000053',
    name: 'Nước Tăng Lực Sting Dâu 330ml',
    categoryId: 'cat-02',
    unit: PRODUCT_UNIT.Bottle,
    costPrice: 8_000,
    salePrice: 13_000,
    vatPercent: 10,
    supplierId: 'sup-7',
    minStock: 84,
    maxStock: 420,
    isPerishable: false,
    shelfLifeDays: 300,
  },
  {
    id: 'prd-012',
    sku: 'CK-DRINK-06',
    barcode: '8934588000060',
    name: 'Trà Xanh Không Độ Chai 500ml',
    categoryId: 'cat-02',
    unit: PRODUCT_UNIT.Bottle,
    costPrice: 7_000,
    salePrice: 12_000,
    vatPercent: 10,
    supplierId: 'sup-7',
    minStock: 72,
    maxStock: 300,
    isPerishable: false,
    shelfLifeDays: 300,
  },
  {
    id: 'prd-013',
    sku: 'CK-DRINK-07',
    barcode: '8934588000077',
    name: 'Bia Tiger Bạc Lon 330ml',
    categoryId: 'cat-02',
    unit: PRODUCT_UNIT.Can,
    costPrice: 14_500,
    salePrice: 22_000,
    vatPercent: 10,
    supplierId: 'sup-7',
    minStock: 48,
    maxStock: 240,
    isPerishable: false,
    shelfLifeDays: 365,
  },

  // ── Thức uống pha chế (cat-03) ──────────────────────────────────────────────────
  {
    id: 'prd-014',
    sku: 'CK-FROSTER-01',
    barcode: '8934599000012',
    name: 'Froster Slushie Dâu Ly Lớn 22oz',
    categoryId: 'cat-03',
    unit: PRODUCT_UNIT.Cup,
    costPrice: 9_500,
    salePrice: 25_000,
    vatPercent: 8,
    supplierId: 'sup-1',
    minStock: 60,
    maxStock: 300,
    isPerishable: false,
    shelfLifeDays: 0,
  },
  {
    id: 'prd-015',
    sku: 'CK-COFFEE-01',
    barcode: '8934599000029',
    name: 'Cà Phê Sữa Đá Sài Gòn Ly 16oz',
    categoryId: 'cat-03',
    unit: PRODUCT_UNIT.Cup,
    costPrice: 7_800,
    salePrice: 20_000,
    vatPercent: 8,
    supplierId: 'sup-5',
    minStock: 60,
    maxStock: 250,
    isPerishable: false,
    shelfLifeDays: 0,
  },
  {
    id: 'prd-016',
    sku: 'CK-COFFEE-02',
    barcode: '8934599000036',
    name: 'Bạc Xỉu Đá Ly 16oz',
    categoryId: 'cat-03',
    unit: PRODUCT_UNIT.Cup,
    costPrice: 8_200,
    salePrice: 22_000,
    vatPercent: 8,
    supplierId: 'sup-5',
    minStock: 50,
    maxStock: 220,
    isPerishable: false,
    shelfLifeDays: 0,
  },
  {
    id: 'prd-017',
    sku: 'CK-TEA-01',
    barcode: '8934599000043',
    name: 'Trà Đào Cam Sả Ly 500ml',
    categoryId: 'cat-03',
    unit: PRODUCT_UNIT.Cup,
    costPrice: 11_000,
    salePrice: 29_000,
    vatPercent: 8,
    supplierId: 'sup-5',
    minStock: 40,
    maxStock: 180,
    isPerishable: true,
    shelfLifeDays: 1,
  },

  // ── Bánh kẹo & Snack (cat-04) ──────────────────────────────────────────────────
  {
    id: 'prd-018',
    sku: 'CK-SNACK-01',
    barcode: '8934611000018',
    name: "Snack Lay's Vị Tảo Biển 95g",
    categoryId: 'cat-04',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 14_000,
    salePrice: 22_000,
    vatPercent: 10,
    supplierId: 'sup-1',
    minStock: 48,
    maxStock: 200,
    isPerishable: false,
    shelfLifeDays: 180,
  },
  {
    id: 'prd-019',
    sku: 'CK-SNACK-02',
    barcode: '8934611000025',
    name: 'Bánh Quy Oreo Socola Gói 133g',
    categoryId: 'cat-04',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 16_500,
    salePrice: 26_000,
    vatPercent: 10,
    supplierId: 'sup-5',
    minStock: 36,
    maxStock: 150,
    isPerishable: false,
    shelfLifeDays: 300,
  },
  {
    id: 'prd-020',
    sku: 'CK-SNACK-03',
    barcode: '8934611000032',
    name: 'Socola KitKat 4 Thanh 35g',
    categoryId: 'cat-04',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 10_500,
    salePrice: 17_000,
    vatPercent: 10,
    supplierId: 'sup-5',
    minStock: 60,
    maxStock: 240,
    isPerishable: false,
    shelfLifeDays: 240,
  },
  {
    id: 'prd-021',
    sku: 'CK-SNACK-04',
    barcode: '8934611000049',
    name: 'Snack Poca Khoai Tây Vị Bò 55g',
    categoryId: 'cat-04',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 8_000,
    salePrice: 13_000,
    vatPercent: 10,
    supplierId: 'sup-1',
    minStock: 60,
    maxStock: 240,
    isPerishable: false,
    shelfLifeDays: 180,
  },
  {
    id: 'prd-022',
    sku: 'CK-SNACK-05',
    barcode: '8934611000056',
    name: 'Kẹo Cao Su Cool Air Hộp 56g',
    categoryId: 'cat-04',
    unit: PRODUCT_UNIT.Box,
    costPrice: 15_000,
    salePrice: 24_000,
    vatPercent: 10,
    supplierId: 'sup-8',
    minStock: 30,
    maxStock: 120,
    isPerishable: false,
    shelfLifeDays: 365,
  },

  // ── Sữa & Chế phẩm (cat-05) ────────────────────────────────────────────────────
  {
    id: 'prd-023',
    sku: 'CK-MILK-01',
    barcode: '8934673000014',
    name: 'Sữa Tươi Tiệt Trùng Vinamilk 180ml',
    categoryId: 'cat-05',
    unit: PRODUCT_UNIT.Box,
    costPrice: 6_200,
    salePrice: 10_000,
    vatPercent: 8,
    supplierId: 'sup-2',
    minStock: 60,
    maxStock: 240,
    isPerishable: true,
    shelfLifeDays: 45,
  },
  {
    id: 'prd-024',
    sku: 'CK-MILK-02',
    barcode: '8934673000021',
    name: 'Sữa Chua Uống Probi Lốc 5 Chai',
    categoryId: 'cat-05',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 28_000,
    salePrice: 42_000,
    vatPercent: 8,
    supplierId: 'sup-2',
    minStock: 24,
    maxStock: 96,
    isPerishable: true,
    shelfLifeDays: 30,
  },
  {
    id: 'prd-025',
    sku: 'CK-MILK-03',
    barcode: '8934673000038',
    name: 'Sữa Chua Có Đường Vinamilk Hộp 100g',
    categoryId: 'cat-05',
    unit: PRODUCT_UNIT.Piece,
    costPrice: 5_000,
    salePrice: 8_500,
    vatPercent: 8,
    supplierId: 'sup-2',
    minStock: 48,
    maxStock: 200,
    isPerishable: true,
    shelfLifeDays: 25,
  },
  {
    id: 'prd-026',
    sku: 'CK-MILK-04',
    barcode: '8934673000045',
    name: 'Phô Mai Con Bò Vui Vẻ 8 Miếng',
    categoryId: 'cat-05',
    unit: PRODUCT_UNIT.Box,
    costPrice: 32_000,
    salePrice: 48_000,
    vatPercent: 8,
    supplierId: 'sup-2',
    minStock: 18,
    maxStock: 72,
    isPerishable: true,
    shelfLifeDays: 90,
  },

  // ── Mì & Thực phẩm khô (cat-06) ──────────────────────────────────────────────
  {
    id: 'prd-027',
    sku: 'CK-NOODLE-01',
    barcode: '8934563000017',
    name: 'Mì Hảo Hảo Tôm Chua Cay Gói 75g',
    categoryId: 'cat-06',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 3_800,
    salePrice: 7_000,
    vatPercent: 8,
    supplierId: 'sup-3',
    minStock: 120,
    maxStock: 600,
    isPerishable: false,
    shelfLifeDays: 180,
  },
  {
    id: 'prd-028',
    sku: 'CK-NOODLE-02',
    barcode: '8934563000024',
    name: 'Mì Ly Modern Lẩu Thái 65g',
    categoryId: 'cat-06',
    unit: PRODUCT_UNIT.Cup,
    costPrice: 9_500,
    salePrice: 16_000,
    vatPercent: 8,
    supplierId: 'sup-3',
    minStock: 60,
    maxStock: 240,
    isPerishable: false,
    shelfLifeDays: 180,
  },
  {
    id: 'prd-029',
    sku: 'CK-NOODLE-03',
    barcode: '8934563000031',
    name: 'Phở Ăn Liền Đệ Nhất Bò 68g',
    categoryId: 'cat-06',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 6_800,
    salePrice: 12_000,
    vatPercent: 8,
    supplierId: 'sup-3',
    minStock: 48,
    maxStock: 200,
    isPerishable: false,
    shelfLifeDays: 180,
  },
  {
    id: 'prd-030',
    sku: 'CK-DRYFOOD-01',
    barcode: '8934563000048',
    name: 'Cá Ngừ Ngâm Dầu Hộp 185g',
    categoryId: 'cat-06',
    unit: PRODUCT_UNIT.Box,
    costPrice: 22_000,
    salePrice: 34_000,
    vatPercent: 8,
    supplierId: 'sup-4',
    minStock: 24,
    maxStock: 96,
    isPerishable: false,
    shelfLifeDays: 720,
  },

  // ── Hàng tiêu dùng (cat-07) ────────────────────────────────────────────────────
  {
    id: 'prd-031',
    sku: 'CK-HOUSE-01',
    barcode: '8934821000019',
    name: 'Khăn Giấy Ướt Circle K Gói 20 Tờ',
    categoryId: 'cat-07',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 8_500,
    salePrice: 15_000,
    vatPercent: 10,
    supplierId: 'sup-6',
    minStock: 30,
    maxStock: 120,
    isPerishable: false,
    shelfLifeDays: 540,
  },
  {
    id: 'prd-032',
    sku: 'CK-HOUSE-02',
    barcode: '8934821000026',
    name: 'Pin Alkaline AA Vỉ 2 Viên',
    categoryId: 'cat-07',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 18_000,
    salePrice: 30_000,
    vatPercent: 10,
    supplierId: 'sup-6',
    minStock: 20,
    maxStock: 80,
    isPerishable: false,
    shelfLifeDays: 1080,
  },
  {
    id: 'prd-033',
    sku: 'CK-HOUSE-03',
    barcode: '8934821000033',
    name: 'Bàn Chải Đánh Răng P/S Du Lịch',
    categoryId: 'cat-07',
    unit: PRODUCT_UNIT.Piece,
    costPrice: 12_000,
    salePrice: 20_000,
    vatPercent: 10,
    supplierId: 'sup-6',
    minStock: 18,
    maxStock: 72,
    isPerishable: false,
    shelfLifeDays: 1080,
  },
  {
    id: 'prd-034',
    sku: 'CK-HOUSE-04',
    barcode: '8934821000040',
    name: 'Dầu Gội Clear Gói 6ml Hộp 12',
    categoryId: 'cat-07',
    unit: PRODUCT_UNIT.Box,
    costPrice: 26_000,
    salePrice: 42_000,
    vatPercent: 10,
    supplierId: 'sup-6',
    minStock: 12,
    maxStock: 60,
    isPerishable: false,
    shelfLifeDays: 900,
  },

  // ── Kem & Đồ đông lạnh (cat-08) ──────────────────────────────────────────────
  {
    id: 'prd-035',
    sku: 'CK-ICE-01',
    barcode: '8934902000016',
    name: 'Kem Que Merino Socola 60ml',
    categoryId: 'cat-08',
    unit: PRODUCT_UNIT.Piece,
    costPrice: 6_500,
    salePrice: 12_000,
    vatPercent: 10,
    supplierId: 'sup-8',
    minStock: 48,
    maxStock: 200,
    isPerishable: true,
    shelfLifeDays: 365,
  },
  {
    id: 'prd-036',
    sku: 'CK-ICE-02',
    barcode: '8934902000023',
    name: 'Kem Hộp Celano Vani 450ml',
    categoryId: 'cat-08',
    unit: PRODUCT_UNIT.Box,
    costPrice: 42_000,
    salePrice: 65_000,
    vatPercent: 10,
    supplierId: 'sup-8',
    minStock: 12,
    maxStock: 48,
    isPerishable: true,
    shelfLifeDays: 365,
  },
  {
    id: 'prd-037',
    sku: 'CK-ICE-03',
    barcode: '8934902000030',
    name: 'Xúc Xích Đông Lạnh C.P Gói 500g',
    categoryId: 'cat-08',
    unit: PRODUCT_UNIT.Pack,
    costPrice: 48_000,
    salePrice: 72_000,
    vatPercent: 8,
    supplierId: 'sup-4',
    minStock: 10,
    maxStock: 40,
    isPerishable: true,
    shelfLifeDays: 120,
    status: RECORD_STATUS.Inactive,
  },
];

/** Danh sách sản phẩm đã điền đủ tên danh mục & nhà cung cấp. */
export const mockProducts: Product[] = rawProducts.map((raw) => ({
  id: raw.id,
  sku: raw.sku,
  barcode: raw.barcode,
  name: raw.name,
  categoryId: raw.categoryId,
  categoryName: categoryNameById(raw.categoryId),
  unit: raw.unit,
  costPrice: raw.costPrice,
  salePrice: raw.salePrice,
  vatPercent: raw.vatPercent,
  supplierId: raw.supplierId,
  supplierName: supplierNameById(raw.supplierId),
  minStock: raw.minStock,
  maxStock: raw.maxStock,
  isPerishable: raw.isPerishable,
  shelfLifeDays: raw.shelfLifeDays,
  imageUrl: '',
  status: raw.status ?? RECORD_STATUS.Active,
  createdAt: '2025-01-05',
}));

/** Sản phẩm đang kinh doanh (loại bỏ hàng ngừng bán). */
export const sellableProducts = mockProducts.filter(
  (product) => product.status === RECORD_STATUS.Active,
);

/** Tra cứu sản phẩm theo id. */
export const productById = (id: string): Product | undefined =>
  mockProducts.find((product) => product.id === id);

/** Tra cứu sản phẩm theo mã vạch – dùng cho máy quét tại POS. */
export const productByBarcode = (barcode: string): Product | undefined =>
  mockProducts.find((product) => product.barcode === barcode.trim());

/** Lợi nhuận gộp trên một đơn vị. */
export const grossProfitPerUnit = (product: Product): number =>
  product.salePrice - product.costPrice;

/** Tỷ suất lợi nhuận gộp (%). */
export const marginPercent = (product: Product): number =>
  product.salePrice === 0
    ? 0
    : (grossProfitPerUnit(product) / product.salePrice) * 100;