import type { Supplier } from '@/types';

/**
 * Module 6 – Nhà cung cấp.
 *
 * `id` giữ nguyên dạng `sup-n` vì các sản phẩm ở `mockData/products.ts`
 * tham chiếu trực tiếp tới các id này.
 */
export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    code: 'NCC-001',
    name: 'Công Ty TNHH Pepsico Việt Nam',
    taxCode: '0300845912',
    phone: '028 3821 9999',
    email: 'contact@pepsico.com.vn',
    address: 'Tầng 5, Toà nhà Sheraton, 88 Đồng Khởi, Quận 1, TP.HCM',
    categories: ['Nước giải khát', 'Snack & Bánh kẹo'],
    paymentTerms: 'Công nợ 30 ngày',
    totalDebt: 125_000_000,
    totalOrders: 48,
    status: 'Active',
    createdAt: '2025-01-10',
  },
  {
    id: 'sup-2',
    code: 'NCC-002',
    name: 'Công Ty Cổ Phần Sữa Việt Nam (Vinamilk)',
    taxCode: '0300588569',
    phone: '028 5415 5555',
    email: 'vinamilk@vinamilk.com.vn',
    address: '10 Tân Trào, Phường Tân Phú, Quận 7, TP.HCM',
    categories: ['Sữa & Chế phẩm', 'Thức uống bổ dưỡng'],
    paymentTerms: 'Công nợ 15 ngày',
    totalDebt: 84_500_000,
    totalOrders: 62,
    status: 'Active',
    createdAt: '2025-01-12',
  },
  {
    id: 'sup-3',
    code: 'NCC-003',
    name: 'Công Ty TNHH Acecook Việt Nam',
    taxCode: '0300600123',
    phone: '028 3815 4064',
    email: 'info@acecookvietnam.com',
    address: 'Lô II-3, Đường CN1, KCN Tân Bình, Quận Tân Phú, TP.HCM',
    categories: ['Đồ ăn nhanh', 'Mì ăn liền'],
    paymentTerms: 'Công nợ 30 ngày',
    totalDebt: 96_000_000,
    totalOrders: 55,
    status: 'Active',
    createdAt: '2025-01-15',
  },
  {
    id: 'sup-4',
    code: 'NCC-004',
    name: 'Công Ty TNHH Thực Phẩm C.P. Việt Nam',
    taxCode: '3600248900',
    phone: '0251 3836 251',
    email: 'info@cp.com.vn',
    address: 'KCN Biên Hoà 2, Thành phố Biên Hoà, Đồng Nai',
    categories: ['Đồ ăn nhanh', 'Thực phẩm tươi sống'],
    paymentTerms: 'Thanh toán ngay',
    totalDebt: 0,
    totalOrders: 34,
    status: 'Active',
    createdAt: '2025-02-01',
  },
  {
    id: 'sup-5',
    code: 'NCC-005',
    name: 'Công Ty TNHH Nestlé Việt Nam',
    taxCode: '3600170068',
    phone: '028 3911 3737',
    email: 'consumer.services@vn.nestle.com',
    address: 'Tầng 5, Toà nhà Empress Tower, 138-142 Hai Bà Trưng, Quận 1, TP.HCM',
    categories: ['Cà phê & Cacao', 'Bánh kẹo'],
    paymentTerms: 'Công nợ 45 ngày',
    totalDebt: 142_000_000,
    totalOrders: 40,
    status: 'Active',
    createdAt: '2025-02-10',
  },
  {
    id: 'sup-6',
    code: 'NCC-006',
    name: 'Công Ty TNHH Quốc Tế Unilever Việt Nam',
    taxCode: '0300874115',
    phone: '028 5413 5686',
    email: 'tuvankhachhang@unilever.com',
    address: 'Lô A2-3, KCN Tây Bắc Củ Chi, Xã Tân An Hội, Củ Chi, TP.HCM',
    categories: ['Mỹ phẩm & Tiện ích'],
    paymentTerms: 'Công nợ 30 ngày',
    totalDebt: 45_000_000,
    totalOrders: 22,
    status: 'Active',
    createdAt: '2025-02-18',
  },
  {
    id: 'sup-7',
    code: 'NCC-007',
    name: 'Công Ty TNHH Nước Giải Khát Suntory PepsiCo',
    taxCode: '0303645020',
    phone: '028 3821 9490',
    email: 'cskh@suntorypepsico.vn',
    address: 'Tầng 5, Toà nhà Sheraton, 88 Đồng Khởi, Quận 1, TP.HCM',
    categories: ['Nước giải khát', 'Thức uống bổ dưỡng'],
    paymentTerms: 'Công nợ 30 ngày',
    totalDebt: 68_400_000,
    totalOrders: 51,
    status: 'Active',
    createdAt: '2025-03-04',
  },
  {
    id: 'sup-8',
    code: 'NCC-008',
    name: 'Công Ty Cổ Phần Kem Kido',
    taxCode: '0302705302',
    phone: '028 3827 0468',
    email: 'info@kdc.vn',
    address: '138-142 Hai Bà Trưng, Phường Đa Kao, Quận 1, TP.HCM',
    categories: ['Kem & Đông lạnh', 'Bánh kẹo'],
    paymentTerms: 'Công nợ 15 ngày',
    totalDebt: 31_200_000,
    totalOrders: 28,
    status: 'Active',
    createdAt: '2025-03-22',
  },
  {
    id: 'sup-9',
    code: 'NCC-009',
    name: 'Công Ty TNHH Thương Mại Bao Bì Minh Phát',
    taxCode: '0311244566',
    phone: '028 6265 3311',
    email: 'sales@minhphatpack.vn',
    address: '124 Lê Trọng Tấn, Quận Tân Phú, TP.HCM',
    categories: ['Vật tư & Bao bì'],
    paymentTerms: 'Thanh toán ngay',
    totalDebt: 0,
    totalOrders: 15,
    status: 'Inactive',
    createdAt: '2025-04-09',
  },
];

/** Tra cứu nhà cung cấp theo id. */
export const supplierById = (id: string): Supplier | undefined =>
  mockSuppliers.find((supplier) => supplier.id === id);

/** Tên nhà cung cấp theo id. */
export const supplierNameById = (id: string): string =>
  supplierById(id)?.name ?? 'Không xác định';
