server:
  port: 8080

spring:
  application:
    name: cuahangtienloi
#  security:
#    user:
#      name: admin
#      password: admin

  config:
    import: optional:file:.env[.properties], optional:file:backend/.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cuahangtienloi}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 600000
      keepalive-time: 60000
#      initialization-fail-timeout: 0         # Cho phép app khởi động tiếp mà không crash nếu Neon đang sleep
#      validation-timeout: 5000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT phải nằm ngoài spring:
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

# CORS cũng phải nằm ngoài spring:
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    enabled: false

logging:
  level:
    root: INFO
    com.erp.cuahangtienloi: DEBUG
    org.hibernate.SQL: DEBUG
