
export const initialBranches: any[] = [
    {
        id: 'CK-0101',
        name: 'Circle K - Quận 1 (Bùi Viện)',
        addressLine: '20 Bùi Viện, Phường Phạm Ngũ Lão',
        district: 'Quận 1, TP.HCM',
        phone: '028 3836 8886',
        managerName: 'Trần Văn Anh',
        employeeCount: 18,
        status: 'Active',
        openedAt: '2019-03-15',
    },
    {
        id: 'CK-0102',
        name: 'Circle K - Quận 3 (Trần Quốc Thảo)',
        addressLine: '145 Trần Quốc Thảo, Phường Võ Thị Sáu',
        district: 'Quận 3, TP.HCM',
        phone: '028 3930 2277',
        managerName: 'Lê Thị Hồng',
        employeeCount: 14,
        status: 'Active',
        openedAt: '2020-07-01',
    },
    {
        id: 'CK-0103',
        name: 'Circle K - TP.Thủ Đức (Thảo Điền)',
        addressLine: '92 Quốc lộ 13, Phường Thảo Điền',
        district: 'TP. Thủ Đức, TP.HCM',
        phone: '028 3744 5566',
        managerName: 'Nguyễn Minh Tuấn',
        employeeCount: 12,
        status: 'Active',
        openedAt: '2021-11-20',
    },
    {
        id: 'CK-0201',
        name: 'Circle K - Hà Nội (Hoàn Kiếm)',
        addressLine: '55 Bà Triệu, Phường Hàng Bài',
        district: 'Hoàn Kiếm, Hà Nội',
        phone: '024 3942 8899',
        managerName: 'Phạm Đức Long',
        employeeCount: 16,
        status: 'Active',
        openedAt: '2022-04-10',
    },
    {
        id: 'CK-0104',
        name: 'Circle K - Quận 7 (Phú Mỹ Hưng)',
        addressLine: '8 Nguyễn Văn Linh, Phường Tân Phong',
        district: 'Quận 7, TP.HCM',
        phone: '028 5412 3344',
        managerName: 'Võ Ngọc Mai',
        employeeCount: 9,
        status: 'Inactive',
        openedAt: '2023-09-05',
    },
];
